name: Feature Request
description: Request a feature or enhancement
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: before-posting
    attributes:
      label: "⚠️ Before submitting, please verify the following: ⚠️"
      description: All conditions are **required**. Your issue can be closed if these are checked incorrectly.
      options:
        - label: The Organic Maps app is **up to date**.
          required: true
        - label: This feature is **not** already requested on Github (I've searched it).
          required: true
        - label: I agree to follow Organic Maps [Code of Conduct](https://github.com/organicmaps/organicmaps/blob/master/docs/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md).
          required: true
        - label: I've already [started a discussion thread](https://github.com/organicmaps/organicmaps/discussions/categories/ideas).
          required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - iOS
        - Android
        - HarmonyOS
    validations:
      required: false
  - type: input
    id: osVersion
    attributes:
      label: OS Version
      description: "What is the verion of your operating system that your encountering this bug on?"
      placeholder: "Example: iOS 15.4.1 or Android 12.1.0_r4 or HarmonyOS 2.0.0.222"
    validations:
      required: false
  - type: input
    id: prevalence
    attributes:
      label: Feature prevalence
      description: "How often would you or others use this feature?"
      placeholder: "Example: Whenever I (...) (1-2 times a week)"
    validations:
      required: true
  - type: textarea
    id: features-description
    attributes:
      label: Requested features description
      description: Please provide a clear description of the requested feature.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      value: |
        When clicking on the (...), (...) should be an option.
        ...
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Any additional information related to the request. 📷 Screenshots and examples are always useful!
    validations:
      required: false
